### ISSUE TITLE
OpenID login oddity

### ISSUE THREAD

**Issue by greggrossmeier** [talkatv/talkatv#15]
I'm getting

<pre>
error:Invalid OpenID message.
ns:http://specs.openid.net/auth/2.0
</pre>

when trying to log in. I can log in, as long as I press the back button where I get to the page that lets me share information (the page that has the "Automatically share my information with this site" question).

Using SimpleID 0.8.1

**Comment by joar** [comment]
This seems to be a SimpleID issue. It occurs if you are not already logged in when you log in on talkatv with your SimpleID OpenID.

Testing with Google OpenID it works despite me having to sign in, this seems to be an issue with SimpleID, where the solution is to sign in to your SimpleID provider before you register/log in with on talkatv.
