### ISSUE TITLE
Confusion after OpenID login

### ISSUE THREAD

**Issue by greggrossmeier** [talkatv/talkatv#16]
I am brought back to the talka.tv login page with my name, email, and openid urls filled it (empty password). I can just click "login" and it works, but it is confusing if I need to enter a password or not.

**Comment by joar** [comment]
The problem lies in that I use the same WTForm for regular registration and OpenID "profile" registration.

The solution would be to separate the OpenID-confirm-profile form and the registration form.

**Comment by joar** [comment]
- Move password changing to a separate page.

**Comment by joar** [comment]
Separated the password change from edit profile in 41052f28a9505b1f151a9ac56a453e3fe2038d27
