### ISSUE TITLE
Update README for extra packages to install

### ISSUE THREAD

**Issue by arthurlutz** [talkatv/talkatv#41]
Unless I got something wrong, I had to install the following extra packages (not mentioned in the documentation) : 

$ history | grep install
 9975  pip install mig
 9977  pip install flask-ext-bootstrap
 9978  pip install flask-bootstrap
 9983  pip install flask-openid
 9986  pip install flask-sqlalchemy
 9993  sudo apt-get -uVf install python-bcrypt
10042  pip install python-webfinger
10044  pip install flask-wtf

**Comment by joar** [comment]
What does `history | grep 'python setup.py develop'` say? It seems that either you forgot to run that line, or the command failed.

**Comment by arthurlutz** [comment]
I am sure I did "python setup.py develop", am pretty sure it did not fail (otherwise I would have filed a bug at that point or fixed it somehow). Not in my terminal history anymore, can't check.

**Comment by joar** [comment]
`python setup.py develop` should install [the packages](https://github.com/talkatv/talkatv/blob/master/setup.py#L46) mentioned. I'm not sure why they weren't installed.

It may be that you did not [activate the virtualenv](https://pypi.python.org/pypi/virtualenv#activate-script) (`source bin/activate`) when trying to run the talka.tv application. Besides that I wouldn't be able to reproduce the issue.
