### ISSUE TITLE
Fallback for non-javascript-enabled user agents

### ISSUE THREAD

**Issue by joar** [talkatv/talkatv#8]
It might be possible to render a `<noscript>` with a link to a comment page. It's possible to pull the page URI from the `Referrer`, then do a `30(1|2)` to `/comment/?page=$URL` for further permalinkability. For user agents without referrer data, the 3rd party page may render the direct URL to the comment page (`/comment/?page=$URL`) instead.

**Comment by warpr** [comment]
You may want to experiment with an `<iframe>` inside the `<noscript>`.  I do not know if it would work, but it sounds like it should :)

**Comment by jfmcbrayer** [comment]
IMO there's nothing to stop a static blog renderer from building in the direct URL to the comment page, so that would be a lot more reliable than Referrer.

An iframe that pulls in the content of the comment page, with the static link to the comment page as its alternate content, is probably the best that can be done. Browsers supporting iframe (I'm thinking of, e.g., Firefox with NoScript installed) will get a reasonable comment experience, while lynx and such will get a link to the comments page.

**Comment by joar** [comment]
@jfmcbrayer Yes, referrer may be used as a fallback from the URL rendering, since there are a log of blog engines out there we can't put up code snippets with instructions for all of them, so it's mostly up to the site owner to implement it or not. Referrer on the other hand may work as long as the user agent supports it, and will shorten the implementation step for the site owner, but I agree with you that it's not a sure way to make it work.

We should therefore be able to detect by referral and then immediately redirect to the comment page with the page URL, so that the commenter will get a permalinkable page, and not one that is dependent on referrer, the referrer detection is just an intermediate step to redirect the commenter to the appropriate URL for the comment page.

We should then encourage site owners to render the full URL to the comment page in the talkatv code snippet and include directions on what part of the URL that should be included.

**Comment by joar** [comment]
Added in-app comment listing in c684d7b14ef44b39e1ded26d68f103f39bb756b0.

**Comment by joar** [comment]
Closing this issue and creating a new issue specifically for posting comments from a non-javascript user agent.

**Comment by joar** [comment]
@jfmcbrayer Actually, I discovered that static page generators aren't aware of their base URL (e.g http://wandborg.se). It's not a show stopper though, I just added the base URL manually to my http://wandborg.se post template.
